name: notex
description: A new Flutter project.
publish_to: "none"
version: 0.1.0+1
uses-material-design: true

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  auth0_flutter: ^1.2.1
  cloud_firestore: ^4.8.4
  confetti: ^0.7.0
  cupertino_icons: ^1.0.5
  file_picker: ^5.3.3
  firebase_auth: ^4.7.2
  firebase_core: ^2.15.0
  firebase_storage: ^11.2.5
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.2
  flutter_slidable: ^3.0.0
  font_awesome_flutter: ^10.5.0
  google_fonts: ^5.1.0
  http: ^1.1.0
  path_provider: ^2.1.0
  provider: ^6.0.5
  read_pdf_text: ^0.2.1
  url_launcher: ^6.1.12
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assests/logo5.png
    - assests/mascot-blush.png
    - assests/th.jpeg
    - assests/hackathons.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
